image: dclong/gitpod
tasks:
  - before: export PATH=/home/gitpod/.local/bin:$PATH
    init: ln -s /workspace/blog/main.py /workspace/.pip-modules/bin/blog
  - command: pip3 install --user pelican
ports:
  - port: 8888
