image: dclong/jupyterhub-ds
tasks:
  - before: export PATH=/home/gitpod/.local/bin:$PATH
    init: ln -s /workspace/blog/main.py /workspace/.pip-modules/bin/blog
    command: nvim --headless +"call dein#install()" +qall && xinstall svim -ic
  - command: pip3 install --user pelican
ports:
  - port: 8888
